name: Release
on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'
jobs:
  call-org-release:
    uses: your-org/.github/.github/workflows/reusable-release.yml@main
    with:
      release-type: sdk
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      PACKAGE_REGISTRY_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
